DJANGOFRAME/Coffe_second_project/coffe_project/coffe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from products import views
from django.conf import settings
from django.views.generic import TemplateView
from django.conf.urls.static import static

urlpatterns = [
    path('', TemplateView.as_view(template_name='base.html'), name='home'),
    path("admin/", admin.site.urls),
    # path('', views.home, name="home"),
    path("products/", include("products.urls")),
    path("users/", include("users.urls")),
    path("orders/", include("orders.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DJANGOFRAME/Coffe_second_project/coffe_project/orders/urls.py
from django.urls import path
from .views import CreateOrderView, OrderDetailView

app_name = "orders"

urlpatterns = [
    path(
        "create_order/<int:product_id>/", CreateOrderView.as_view(), name="create_order"
    ),
    path(
        "order_detail/<int:order_id>/", OrderDetailView.as_view(), name="order_detail"
    ),
]

DJANGOFRAME/Coffe_second_project/coffe_project/products/urls.py
from django.urls import path
from .views import (
    ProductFormView,
    ProductListView,
    main,
    product_detail,
    ProductListAPI,
    menu,
)


app_name = "products"

urlpatterns = [
    path("main/", main, name="main"),
    path("product_detail/<int:product_id>/", product_detail, name="product_detail"),
    path("menu/", menu, name="product_menu"),
    path("add/", ProductFormView.as_view(), name="add_product"),
    path("product_list/", ProductListView.as_view(), name="product_list"),
    path("api/", ProductListAPI.as_view(), name="product_list_api"),
]

DJANGOFRAME/Coffe_second_project/coffe_project/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="users:login"), name="logout"),
    path(
        "register/",
        RegisterView.as_view(template_name="registration/register.html"),
        name="register",
    ),
]

DJANGOFRAME/Coffe_second_project/coffe_project/products/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    name = models.TextField(max_length=200, verbose_name="name")
    description = models.TextField(max_length=300, verbose_name="description")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="price")
    available = models.BooleanField(default=True, verbose_name="available")
    photo = models.ImageField(
        upload_to="logos", null=True, blank=True, verbose_name="photo"
    )

    def __str__(self):
        return self.name

DJANGOFRAME/Coffe_second_project/coffe_project/products/forms.py
from django import forms
from .models import Product


class ProductForm(forms.Form):
    name = forms.CharField(max_length=200, label="Name")
    description = forms.CharField(max_length=300, label="Description")
    price = forms.DecimalField(max_digits=10, decimal_places=2, label="Price")
    available = forms.BooleanField(initial=True, label="Available", required=False)
    photo = forms.ImageField(label="Photo", required=False)

    def save(self):
        data = self.cleaned_data
        Product.objects.create(
            name=data["name"],
            description=data["description"],
            price=data["price"],
            available=data["available"],
            photo=data["photo"],
        )

DJANGOFRAME/Coffe_second_project/coffe_project/products/views.py
from django.shortcuts import render, get_object_or_404
from .forms import ProductForm
from .models import Product
from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from django.views.generic import ListView
from rest_framework.views import APIView
from .serializers import ProductSerializer
from rest_framework.response import Response


# Create your views here.
# def home(request):
#     return render(request, 'base.html')


def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, "product_detail.html", {"product": product})


def menu(request):
    product = Product.objects.first()
    return render(request, "menu.html", {"product": product})


def main(request):
    return render(request, "main.html")


class ProductListView(ListView):
    model = Product
    template_name = "product_list.html"
    context_object_name = "products"


class ProductFormView(FormView):
    template_name = "add_product.html"
    form_class = ProductForm
    success_url = reverse_lazy("products:product_list")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ProductListAPI(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request):
        products = Product.objects.all()
        serializer = ProductSerializer(products, many=True)
        return Response(serializer.data)

DJANGOFRAME/Coffe_second_project/coffe_project/products/templates/add_product.html
<h1>Add product</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% comment %} {{ form.as_p }} {% endcomment %}
 

    <div class="mb-4">
    <label for="{{ form.name.id_for_label }}" class="block text-sm font-medium">Name</label>
    {{ form.name }}
    {% if form.name.errors %}
      <p class="text-red-500 text-sm">{{ form.name.errors }}</p>
    {% endif %}
    </div>
    <div class="mb-4">
        <label for="{{ form.description.id_for_label }}" class="block text-sm font-medium">Description</label>
        {{ form.description }}
        {% if form.price.errors %}
        <p class="text-red-500 text-sm">{{ form.price.errors }}</p>
        {% endif %}
    </div>
    <div class="mb-4">
        <label for="{{ form.price.id_for_label }}" class="block text-sm font-medium">Price</label>
        {{ form.price }}
        {% if form.price.errors %}
        <p class="text-red-500 text-sm">{{ form.price.errors }}</p>
        {% endif %}
    </div>
    <div class="mb-4">
        <label class="inline-flex items-center">
            <span class="ml-2 text-sm text-gray-700">{{ form.available.label }}</span>
            {{ form.available }}
           
        </label>

        {% if form.available.errors %}
            <p class="text-red-500 text-sm">{{ form.available.errors }}</p>
        {% endif %}
    </div>
    <div class="mb-4">
        <label for="id_photo" class="inline-flex items-center">
            <span class="ml-2 text-sm text-gray-700">Upload Photo</span>
            {{ form.photo }}
        </label>

        {% if form.available.errors %}
            <p class="text-red-500 text-sm">{{ form.photo.errors }}</p>
        {% endif %}
    </div>
       <button type="submit">Add</button>
   
        <button type="button" class="btn">Basic</button>

</form>

DJANGOFRAME/Coffe_second_project/coffe_project/products/templates/main.html
{% extends 'base.html' %}

{% block content %}
<div class="min-h-screen flex items-center justify-center bg-gray-100 " id="main-photo">
  <div class="space-y-6 text-center main-container">
    <h1 class="text-4xl font-bold text-gray-800 mb-8 main-title">Welcome to Andres Coffee Store ☕</h1>

    <div class="space-y-4" >
      
      <a href="{% url 'products:product_menu' %}" 
         class="block w-60 mx-auto py-3 px-6 bg-yellow-400 text-white font-semibold rounded-lg hover:bg-yellow-500 transition">
        See Menu
      </a>

      
      <a href="{% url 'products:product_list' %}" 
         class="block w-60 mx-auto py-3 px-6 bg-green-500 text-white font-semibold rounded-lg hover:bg-green-600 transition">
        Buy Products
      </a>

      <a href="{% url 'products:add_product' %}" 
         class="block w-60 mx-auto py-3 px-6 bg-blue-500 text-white font-semibold rounded-lg hover:bg-blue-600 transition">
        Add product
      </a>
    </div>
  </div>
</div>
{% endblock %}

DJANGOFRAME/Coffe_second_project/coffe_project/products/templates/menu.html
{% extends "base.html" %}

{% block content %}
    
    <div class="menu">
      <main>
        <h1>CAMPER CAFE</h1>
        <p class="established">Est. 2020</p>
        <hr>
        <section>
          <h2>Coffee</h2>
          <img src="https://cdn.freecodecamp.org/curriculum/css-cafe/coffee.jpg" alt="coffee icon">
            <article class="item">
              <!-- Shows products information -->
              
              <p class="flavor">{{ product.name }}</p><p class="price">${{ product.price }}</p>  <!-- Precio del producto -->
              <div class="description-photo">
                <p class="product-description">{{ product.description }}</p>
              {% if product.photo %}
                  <img src="{{ product.photo.url }}" alt="{{ product.name }}" class="product-photo">
              {% else %}
                  <p>No image available</p>
              {% endif %}
              </div>
          </article>
          <article class="item">
            <p class="flavor">Caramel Macchiato</p><p class="price">3.75</p>
            
          </article>
          <article class="item">
            <p class="flavor">Pumpkin Spice</p><p class="price">3.50</p>
            
          </article>
          <article class="item">
            <p class="flavor">Hazelnut</p><p class="price">4.00</p>
            
          </article>
          <article class="item">
            <p class="flavor">Mocha </p><p class="price">4.50</p>
            
          </article>
        </section>
        <hr>
        <section>
            <h2>Desserts</h2>
            <img src="https://cdn.freecodecamp.org/curriculum/css-cafe/pie.jpg" alt="pie icon">
            <article class="item">
                <p class="dessert ">Donut</p><p class="price">1.50</p>
            </article>
            <article class="item">
                <p class="dessert ">Cherry Pie</p><p class="price">2.75</p>
            </article>
            <article class="item">
                <p class="dessert ">Cheesecake</p><p class="price">3.00</p>
            </article>
            <article class="item">
                <p class="dessert ">Cinnamon Roll</p><p class="price">2.50</p>
            </article>
        </section>
      </main>
      <hr class="bottom-line">
    
    </div >    
    
{% endblock %}

DJANGOFRAME/Coffe_second_project/coffe_project/products/templates/product_detail.html
<!-- product_detail.html -->
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Products Details</title>
    
</head>
<body>
    <article class="item">
        <h2 class="flavor">{{ product.name }}</h2>
        <p class="price">${{ product.price }}</p>
        <p class="description">{{ product.description }}</p>

        {% if product.photo %}
            <img src="{{ product.photo.url }}" alt="{{ product.name }}" class="product-photo">
        {% else %}
            <p>No image available</p>
        {% endif %}
    </article>
</body>
</html>

DJANGOFRAME/Coffe_second_project/coffe_project/products/templates/product_list.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% load static %}

{% block content %}

<h1 class="text-3xl font-bold underline">
      Product List!
    </h1>
{% for product in products %}
    <a href="#" class="group relative block overflow-hidden">
  <button
    class="absolute end-4 top-4 z-10 rounded-full bg-white p-1.5 text-gray-900 transition hover:text-gray-900/75"
  >
    <span class="sr-only">Wishlist</span>

    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="size-4"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"
      />
    </svg>
  </button>
    {% if product.photo %} 
    <img
    src="{{ product.photo.url }}"
    alt="{{ product.name }}"
    class="h-64 w-full object-cover transition duration-500 group-hover:scale-105 sm:h-72"
    />
   {%else%}
            <p style="color: white;" >No photo available</p>
        {%endif%}
  <div class="relative border border-gray-100 bg-white p-6">
    <span class="bg-yellow-400 px-3 py-1.5 text-xs font-medium whitespace-nowrap"> New </span>

    <h3 class="mt-4 text-lg font-medium text-gray-900 name-product">{{ product.name }}</h3>

    <div class="price-available">
        <p class="mt-1.5 text-sm text-gray-700">${{ product.price }}</p>
        {% if product.available %}
    <div class="bg-green-500 text-white p-2 rounded-sm font-semibold text-center">
      Available: Yes
    </div>
  {% else %}
    <div class="bg-red-500 text-white p-2 rounded-sm font-semibold text-center">
      Currently Out of Stock
    </div>
  {% endif %}
    </div>

    <form class="mt-4"  action="{% url 'orders:create_order' product_id=product.id %}" method="post">
        {% csrf_token %}     
      <button
        class="block w-full rounded-sm bg-yellow-400 p-4 text-sm font-medium transition hover:scale-105"
      >
        Add to Cart
      </button>
    </form>
  </div>
</a>


    
{% endfor %}

{% endblock content %}